### ISSUE TITLE
Has this template been updated to consider input/output gate rules?

### ISSUE THREAD

**Issue by rib** [cloudflare/durable-objects-template#11]
Hi, I was a little unsure of whether the code in this template is taking into account the input/output gate rules that are described here: https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/

In particular I wasn't sure about this comment: 
```javascript
    // Return `currentValue`. Note that `this.value` may have been
    // incremented or decremented by a concurrent request when we
    // yielded the event loop to `await` the `storage.put` above!
    // That's why we stored the counter value created by this
    // request in `currentValue` before we used `await`.
```
Ref: https://github.com/cloudflare/durable-objects-template/blob/5759d669971bed5946c74c88ae379ba864af718a/src/index.mjs#L52

My understanding from reading the document about input/output gate rules was that the event loop for the thread handling this durable object would be paused while waiting for the `storage.put` and so there would be no way for any concurrent request to increment/decrement this value?

This is how the input gate rule is described in the blog post above:

> Input gates: While a storage operation is executing, no events shall be delivered to the object except for storage completion events. Any other events will be deferred until such a time as the object is no longer executing JavaScript code and is no longer waiting for any storage operations. We say that these events are waiting for the "input gate" to open

I was also wondering whether input/output gates equally apply to the constructor and maybe that means this use of `blockConcurrencyWhile` is redundant now?:
```javascript
    this.state.blockConcurrencyWhile(async () => {
        let stored = await this.state.storage.get("value");
        this.value = stored || 0;
    })
```

I'm unsure whether I've misunderstood something or perhaps this code was written before the gate rules were introduced?

**Comment by koeninger** [comment]
Templates were written before the introduction of gates, I'll put in PRs to update them
