### ISSUE TITLE
Extend Readme with some usage commands / bug?

### ISSUE THREAD

**Issue by martinklepsch** [cloudflare/durable-objects-template#9]
On a fresh checkout of this repo I get the following output when running `wrangler dev`.

I'm not sure if this is maybe the wrong command or if something else is going wrong. 
 
```
$ wrangler dev

    Your configuration file is missing compatibility_date, so a past date is assumed.
    To get the latest possibly-breaking bug fixes, add this line to your wrangler.toml:

        compatibility_date = "2021-11-06"

    For more information, see: https://developers.cloudflare.com/workers/platform/compatibility-dates

Error: The migration tag for the script was never fetched. This is a bug in wrangler, and we'd appreciate an issue report!
```

 `wrangler 1.19.4` 
 

Would appreciate any guidance! :)

**Comment by martinklepsch** [comment]
I got the project to work with `miniflare` but it required reverting this commit https://github.com/cloudflare/durable-objects-template/commit/5519378a3e553c09873fc0d80cb0257bdb2b03f2 — the call to `blockConcurrencyWhile` would fail inside miniflare.

**Comment by a-robinson** [comment]
Thanks for the report, @martinklepsch!

@xortive does the error message he hit ring any immediate bells or do you want someone else to check into it?

As for `blockConcurrencyWhile` inside miniflare, it was only very recently added as mentioned here: https://github.com/cloudflare/miniflare/issues/45

**Comment by a-robinson** [comment]
@martinklepsch it turns out that `wrangler dev` on Durable Objects needs to be updated to work on scripts that use migrations inside of `wrangler.toml`. It should work for you if you also revert ae8919aabbd0533d99a2da2ca31def36c77c0917.

We'll be fixing that soon, sorry for the problems.

**Comment by a-robinson** [comment]
@xortive has fixed the `wrangler dev` issue in https://github.com/cloudflare/wrangler/pull/2127
